### ISSUE TITLE
怎样把三元组信息导入到neo4j中

### ISSUE THREAD

**Issue by xuymail** [lixiang0/WEB_KG#1]
作者您好，看了您的代码，有一个疑问，不知道怎样将抽出的三元组信息（在您的项目中是以bin格式存储的pickle数据）导入到neo4j数据库中。好像目前项目中并没有 这块的代码，如方便，可否将这块代码公布出来。

另，现在知识图谱结果一般都通过web可视化，关于这块的程序不知您是否已经有了代码？或思路？如方便，也请一并告之。

非常感谢。

**Comment by lixiang0** [comment]
你好。
1.抽取三元组的代码目前还没有上传还在改进,所以还没有上传。思路也比较简单，就是根据百科页面的结构化信息去抽取。不过这种方式也存在问题，也是目前正在改进的地方。
2.导入neo4j的方式，这里给出我的方法：
```
def add_node(tx, name1, relation,name2):
    tx.run("MERGE (a:Node {name: $name1}) "
        "MERGE (b:Node {name: $name2}) "
           "MERGE (a)-[:"+relation+"]-> (b)",
           name1=name1,name2=name2)
```
3.关于可视化，可以使用neo4j中的开源代码改进一下。这里可以给出一个[链接](https://github.com/neo4j-examples/movies-javascript-bolt)
