### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by taoqiongxing** [lixiang0/WEB_KG#10]
你好，我试图用爬取自己想要的网页，这样的话第二步和第三步似乎时必须的，但是我在尝试第二步时出错，不知该如何解决。报错信息依然是:print(pages[0])，IndexError: list index out of range。而实际是存在的

**Comment by lixiang0** [comment]
你好，webpages的目录修改了吗？

**Comment by taoqiongxing** [comment]
是这样的，是我的失误，非常感谢，已经成功跑通
非常感谢您的这个项目

**Comment by lrfelicity** [comment]
> 是这样的，是我的失误，非常感谢，已经成功跑通
> 非常感谢您的这个项目
请问你是怎样解决的

**Comment by taoqiongxing** [comment]
更改了webpages的目录后可以解决之一问题
另外，我是在windows上运行的，某些某些运行错误也做了更正，修改后的完整代码已上传

在2019-07-17 15:37:39，lrfelicitynotifications@github.com写道：

是这样的，是我的失误，非常感谢，已经成功跑通
非常感谢您的这个项目
请问你是怎样解决的

**Comment by taoqiongxing** [comment]
更改了webpages的目录后可以解决这个问题
另外，我是在windows上运行的，某些在windows上的运行错误也做了更正，修改后的代码我也有上传

在2019-07-17 15:37:39，lrfelicitynotifications@github.com写道：

是这样的，是我的失误，非常感谢，已经成功跑通
非常感谢您的这个项目
请问你是怎样解决的
