### ISSUE TITLE
url_manager, html_downloader, html_parser无法导入

### ISSUE THREAD

**Issue by SeptSky** [lixiang0/WEB_KG#13]

**Comment by SeptSky** [comment]
import url_manager, html_downloader, html_parser
本人Python新手，请问上面三个包如何安装呢？我在VS Code下提示无法找到相应的模块，Python版本为3.6.8，网上也找不到相关资料。

谢谢！

**Comment by zqqqqq1** [comment]
这是在spider 文件夹下的三个py文件

**Comment by SeptSky** [comment]
> 
> 
> 这是在spider 文件夹下的三个py文件

谢谢答复。
很奇怪在同一文件夹下，VS Code依然提示“unresolved import 'html_downloader'”。第一次打开就提示这样的错误。

**Comment by SeptSky** [comment]
改为from spider import url_manager, html_downloader, html_parser就可以了，妥妥的Python新手。
