### ISSUE TITLE
windows无法运行，一运行就save state

### ISSUE THREAD

**Issue by xiongma** [lixiang0/WEB_KG#2]
windows无法运行，一运行就save state

**Comment by lixiang0** [comment]
已修改代码，重新拉一下代码，再试试。

**Comment by dupanfei1** [comment]
windows下还是save state 也有craw但是后面程序运行报错：fail to extract.. [Errno 2] No such file or directory: './info-para/.txt'

**Comment by lixiang0** [comment]
不好意思，我没有windows的环境。
看这个问题是linux和windows的文件路径中反斜杆的原因。
windows中是‘\’，而linux中是'/'，本项目是在ubuntu中开发的。所以路径都是'/'。
你可以依次吧报错中的路径改成'\\'即可。 @dupanfei1

**Comment by dupanfei1** [comment]
好的，谢谢

**Comment by Evaoooos** [comment]
> 好的，谢谢

请问下你在windows中跑出这个项目了吗？
