### ISSUE TITLE
is the Robot named ruben open-source? 

### ISSUE THREAD

**Issue by AlbertChanX** [lixiang0/WEB_KG#3]
[ruben](http://bot.rubenxiao.com/)  

i wonder How can i translate natural language into `Cypher` in Neo4j ?

Thanks for ur attention! ❤️

**Comment by lixiang0** [comment]
hi
1.my robot ruben is not open-source for under developing.
2.in a simple way,you make lots of rules,for example:who is $person,so in cypher is```MATCH (p:Person { name:$person})```.

**Comment by dpny518** [comment]
Great work on this project. but but person node is not from your data, that was default movie data provided by neo4j, it seem most of your nodes are just *, and relationships as well, do you have some suggestions on how to write rules for example, finding answers to what is the largest city by population in china, who is the chairman of china, when was 姚明 born, why is the sun yello, what is the longest river in the world. How can we use the knowledge graph to write cypher querries for this graph.
